# Generated by Django 5.2.4 on 2025-07-23 06:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('国内安卓', '国内安卓'), ('海外安卓', '海外安卓'), ('iOS', 'iOS')], help_text='Enter a book genre (e.g. android_cn,android_oversea,iOS etc.)', max_length=20)),
                ('test', models.CharField(blank=True, help_text='test, no use', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('up_OSVersion', models.TextField(help_text='唯一的系统版本')),
                ('up_cpuModel', models.TextField(help_text='唯一的cpu型号')),
                ('up_gpuModel', models.TextField(help_text='唯一的gpu型号')),
                ('up_resolution', models.TextField(help_text='唯一的分辨率')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceId', models.CharField(help_text='设备编号', max_length=99, primary_key=True, serialize=False)),
                ('brand', models.CharField(help_text='设备品牌', max_length=99)),
                ('name', models.CharField(help_text='设备名称', max_length=99)),
                ('deviceModel', models.CharField(help_text='设备型号', max_length=99)),
                ('OSVersion', models.CharField(help_text='当前版本', max_length=99)),
                ('cpuBrand', models.CharField(help_text='cpu品牌', max_length=99)),
                ('cpuModel', models.CharField(help_text='cpu型号', max_length=99)),
                ('cpuFrequency', models.CharField(help_text='cpu频率', max_length=99)),
                ('cpuCoreNum', models.CharField(help_text='cpu核心数', max_length=99)),
                ('RAM', models.CharField(help_text='RAM', max_length=99)),
                ('gpuBrand', models.CharField(help_text='GPU品牌', max_length=99)),
                ('gpuModel', models.CharField(help_text='GPU型号', max_length=99)),
                ('resolution', models.CharField(help_text='分辨率', max_length=99)),
                ('screenType', models.CharField(help_text='屏幕类型', max_length=99)),
                ('size', models.CharField(help_text='尺寸', max_length=99)),
                ('ROM', models.CharField(help_text='ROM', max_length=99)),
                ('wanmeiOffice', models.CharField(help_text='wanmei-office开通状态', max_length=99)),
                ('MACAddr', models.CharField(help_text='MAC地址', max_length=99)),
                ('assetNumber', models.CharField(help_text='资产编号', max_length=99)),
                ('onlyOne', models.BooleanField(help_text='唯一设备？')),
                ('status', models.CharField(blank=True, choices=[('不可用', '不可用'), ('借出', '借出'), ('可用', '可用')], default='不可用', help_text='设备状态', max_length=10)),
                ('borrower', models.CharField(blank=True, help_text='借用人', max_length=10, null=True)),
                ('dueBackTime', models.DateField(blank=True, help_text='预计归还', null=True)),
                ('genre', models.ForeignKey(help_text='设备分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre')),
            ],
            options={
                'ordering': ['deviceId'],
            },
        ),
        migrations.CreateModel(
            name='LendHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, help_text='操作id', primary_key=True, serialize=False)),
                ('borrower', models.CharField(help_text='借用人', max_length=40)),
                ('action', models.CharField(choices=[('借用', '借用'), ('归还', '归还')], help_text='操作类型', max_length=10)),
                ('actTime', models.DateTimeField(blank=True, help_text='操作时间', null=True)),
                ('actor', models.CharField(choices=[('借用', '借用'), ('归还', '归还')], help_text='操作员', max_length=10)),
                ('device', models.ForeignKey(help_text='设备id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.device')),
            ],
        ),
        migrations.AddField(
            model_name='genre',
            name='up',
            field=models.OneToOneField(help_text='唯一参数', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.uniqueparameter'),
        ),
    ]
