# Generated by Django 5.2.4 on 2025-07-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_OSVersion',
            field=models.TextField(blank=True, help_text='唯一的系统版本', null=True),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_cpuModel',
            field=models.TextField(blank=True, help_text='唯一的cpu型号', null=True),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_gpuModel',
            field=models.TextField(blank=True, help_text='唯一的gpu型号', null=True),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_resolution',
            field=models.TextField(blank=True, help_text='唯一的分辨率', null=True),
        ),
    ]
