# Generated by Django 5.2.4 on 2025-07-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_uniqueparameter_up_osversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='onlyOne',
            field=models.BooleanField(default=False, help_text='唯一设备？'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('国内安卓', '国内安卓'), ('海外安卓', '海外安卓'), ('iOS', 'iOS'), ('all', 'all')], help_text='Enter a book genre (e.g. android_cn,android_oversea,iOS etc.)', max_length=20),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_OSVersion',
            field=models.TextField(blank=True, default='[]', help_text='唯一的系统版本', null=True),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_cpuModel',
            field=models.TextField(blank=True, default='[]', help_text='唯一的cpu型号', null=True),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_gpuModel',
            field=models.TextField(blank=True, default='[]', help_text='唯一的gpu型号', null=True),
        ),
        migrations.AlterField(
            model_name='uniqueparameter',
            name='up_resolution',
            field=models.TextField(blank=True, default='[]', help_text='唯一的分辨率', null=True),
        ),
    ]
